image: registry.gitlab.com/easbarba/onur-cpp:0.2.0

stages:
  - build
  - test

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'

.build_template: &build_definition
  stage: build
  script:
    - cmake -B build -S .
    - cmake --build build

build:linux:
  <<: *build_definition
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - ./build/tests/onur_tests
  dependencies:
    - build:linux
