image: registry.gitlab.com/easbarba/onur-cpp:0.2.0

stages:
  - test

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'main'

Integration Tests:
  stage: test
  script:
    - meson test -C /home/easbarba/app/build
